services:
    prometheus:
        image: prom/prometheus
        container_name: prometheus
        volumes:
        - /docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        - /docker/prometheus/data:/prometheus
        ports:
        - "9090:9090"
        restart: unless-stopped
